fix: trpc の型エラー直す
CaffeBreak/coffee-break pull request #101
Opened 2023-11-01 00:32 UTC by AOI-1up

2023-11-01 00:59 UTC, cffnpwr commented on apps/backend/src/api/endpoint/player.ts
> +  role: z.string(),
これ`VILLAGER | WEREWOLF`のユニオン型がよい

2023-11-01 00:59 UTC, cffnpwr commented on apps/backend/src/api/endpoint/player.ts
> +  status: z.string(),
これもユニオン型

2023-11-01 00:59 UTC, cffnpwr commented on apps/backend/src/api/endpoint/player.ts
> +  roomId: z.string(),
ここは`z.string.optional()`

2023-11-06 02:07 UTC, cffnpwr requested changes

2023-11-06 02:07 UTC, cffnpwr commented on apps/backend/src/api/endpoint/player.ts
> +  role: z.union([z.literal("VILLAGER"), z.literal("WEREWOLF")]),
ここは
```ts
union([z.literal("PENDING"), z.literal("VILLAGER"), z.literal("WEREWOLF")])
```
にする

2023-11-06 02:19 UTC, cffnpwr approved these changes, later dismissed

2023-11-13 03:15 UTC, cffnpwr commented on apps/frontend/package.json
> +    "@trpc/next": "^10.43.2",
消そうね

2023-11-13 05:41 UTC, cffnpwr commented on apps/frontend/package.json
> +    "@trpc/next": "^10.43.2",
消した

2023-11-13 05:43 UTC, yanbaru1331 approved these changes
腹減った

2023-11-13 05:44 UTC, merged